#!/bin/bash
# Install Script for Codex CLI Ultimate Starter Kit
# Bash version (Linux/macOS)

set -e

echo "========================================="
echo "🚀 Installing Codex CLI Ultimate Starter Kit..."
echo "========================================="

CODEX_HOME="$HOME/.codex"
CONFIG_FILE="$CODEX_HOME/config.toml"
BACKUP_FILE="$CODEX_HOME/config.toml.bak"

echo "Checking Codex directory: $CODEX_HOME"

if [ ! -d "$CODEX_HOME" ]; then
    echo "Creating Codex home directory..."
    mkdir -p "$CODEX_HOME"
fi

if [ -f "$CONFIG_FILE" ]; then
    echo "⚠️  Your existing config.toml will be backed up to config.toml.bak"
    echo "   Custom MCP server configurations or profile overrides will need to be re-added."
    echo "Backing up current config.toml to $BACKUP_FILE"
    cp "$CONFIG_FILE" "$BACKUP_FILE"
else
    echo "No existing config.toml found, will create new."
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(dirname "$SCRIPT_DIR")"
DEFAULT_PROFILE="$WORKSPACE_ROOT/config/free.toml"

if [ -f "$DEFAULT_PROFILE" ]; then
    echo "Deploying 'free' profile as active config.toml..."
    cp "$DEFAULT_PROFILE" "$CONFIG_FILE"

    # Replace placeholders with actual paths (POSIX-safe sed)
    sed "s|__WORKSPACE_ROOT__|$WORKSPACE_ROOT|g" "$CONFIG_FILE" > "$CONFIG_FILE.tmp"
    mv "$CONFIG_FILE.tmp" "$CONFIG_FILE"
else
    echo "Error: Default profile not found at $DEFAULT_PROFILE"
    exit 1
fi

CODEX_EXE=$(which codex 2>/dev/null || echo "codex")
echo "Using Codex CLI executable: $CODEX_EXE"

BIN_DIR="$WORKSPACE_ROOT/bin"
mkdir -p "$BIN_DIR"

WRAPPER_PATH="$BIN_DIR/codex"
cat << EOF > "$WRAPPER_PATH"
#!/bin/bash
# Codex CLI Ultimate wrapper script for Bash
# Auto-generated by install.sh — do not edit manually.

WORKSPACE_ROOT="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"

# Real codex binary — detected at install time
CODEX_EXE="$CODEX_EXE"

# Fallback: try PATH but exclude self to prevent infinite loop
resolve_codex() {
    local self_dir self_exe candidate
    self_dir="\$(cd "\$(dirname "\$0")" 2>/dev/null && pwd)" || return 1
    self_exe="\$self_dir/\$(basename "\$0")"
    candidate=\$(command -v codex 2>/dev/null) || return 1
    # If the resolved binary IS this wrapper, give up
    if [ "\$candidate" = "\$self_exe" ] || [ "\$candidate" = "\$0" ]; then
        return 1
    fi
    echo "\$candidate"
}

if [ ! -x "\$CODEX_EXE" ]; then
    CODEX_EXE=\$(resolve_codex) || true
fi

dispatch() {
    local script="\$WORKSPACE_ROOT/scripts/\$1.sh"
    if [ ! -f "\$script" ]; then
        echo "❌ Script not found: \$script" >&2
        exit 1
    fi
    shift
    bash "\$script" "\$@"
}

case "\${1:-}" in
    profile)
        if [ -z "\${2:-}" ]; then
            echo "Usage: codex profile <name>"
            echo "  Try: free, premium, local, ollama, openrouter"
            echo "Available profiles:"
            ls -1 "\$WORKSPACE_ROOT/config"/*.toml 2>/dev/null | sed 's/.*\///' | sed 's/\.toml//' | sed 's/^/  - /'
            exit 1
        fi
        dispatch switch-profile "\$2"
        ;;
    doctor)   dispatch doctor ;;
    update)   dispatch update ;;
    benchmark) dispatch benchmark ;;
    init)      dispatch init-project "$2" "$3";;
    agent)     dispatch load-agent "$2" ;;
	    fetch-docs) dispatch fetch-docs "$2" ;;
    *)
        if [ -z "\$CODEX_EXE" ] || [ ! -x "\$CODEX_EXE" ]; then
            echo "❌ codex not found. Install Codex CLI or set CODEX_EXE." >&2
            exit 1
        fi
        exec "\$CODEX_EXE" "\$@"
        ;;
esac
EOF

chmod +x "$WRAPPER_PATH"
echo "Created Codex wrapper at: $WRAPPER_PATH"

# ── 6. Auto-configure PATH ──────────────────────────────────
echo ""
echo "--- PATH Setup ---"

# Detect CI/non-interactive mode
if [ -n "$CI" ] || [ -n "$GITHUB_ACTIONS" ] || [ -n "$TF_BUILD" ]; then
    echo "  Non-interactive mode detected (CI). Skipping PATH prompt."
    echo "  To enable 'codex' command manually, add to your shell profile:"
    echo "    export PATH=\"$BIN_DIR:\$PATH\""
else
    # Detect shell profile
    SHELL_PROFILE=""
    if [ -n "$ZSH_VERSION" ]; then
        SHELL_PROFILE="${ZDOTDIR:-$HOME}/.zshrc"
    elif [ -n "$BASH_VERSION" ]; then
        SHELL_PROFILE="$HOME/.bashrc"
        # macOS often uses .bash_profile instead of .bashrc for login shells
        [ -f "$HOME/.bash_profile" ] && SHELL_PROFILE="$HOME/.bash_profile"
    fi

    if [ -n "$SHELL_PROFILE" ] && [ -f "$SHELL_PROFILE" ]; then
        if grep -q "$BIN_DIR" "$SHELL_PROFILE" 2>/dev/null; then
            echo "  ✅ bin directory already configured in $SHELL_PROFILE"
        else
            echo "  Would you like to add the bin directory to your PATH automatically?"
            echo "  This adds '$BIN_DIR' to $SHELL_PROFILE so 'codex' is always available."
            printf "  Add bin/ to PATH? (Y/n): "
            read -r RESPONSE </dev/tty 2>/dev/null || RESPONSE=""
            if [ -z "$RESPONSE" ] || [ "$RESPONSE" = "y" ] || [ "$RESPONSE" = "Y" ]; then
                {
                    echo ""
                    echo "# ── Codex CLI Ultimate ─────────────────────────────────"
                    echo "# Added by install.sh on $(date +%Y-%m-%d)"
                    echo "export PATH=\"$BIN_DIR:\$PATH\""
                } >> "$SHELL_PROFILE"
                echo "  ✅ Added to $SHELL_PROFILE"
                echo "     Restart your terminal or run: source $SHELL_PROFILE"
            else
                echo "  Skipping auto-configuration."
                echo "  To enable manually, add this to $SHELL_PROFILE:"
                echo "    export PATH=\"$BIN_DIR:\$PATH\""
            fi
        fi
    else
        echo "  ⚠️  Could not detect a shell profile."
        echo "     To enable 'codex' command, add this to your shell profile:"
        echo "    export PATH=\"$BIN_DIR:\$PATH\""
    fi
fi

# Add to current session
export PATH="$BIN_DIR:$PATH"
echo "  ✅ Added to current session PATH (temporary)."

echo ""
echo "========================================="
echo "🎉 Setup Complete!"
echo "Available commands:"
echo "  codex profile free        - Switch to free OpenRouter"
echo "  codex profile premium     - Switch to premium OpenRouter"
echo "  codex profile local       - Switch to Ollama (local)"
echo "  codex profile ollama      - Switch to ollama.toml config"
echo "  codex profile openrouter  - Switch to openrouter.toml config"
echo "  codex doctor          - Run diagnostics"
echo "  codex init <name>     - Scaffold a new project"
echo "  codex benchmark       - Benchmark model latency"
echo "========================================="
