# Install Script for Codex CLI Ultimate Starter Kit
# Windows PowerShell version

# Error policy: Stop — installation must succeed or fail clearly
$ErrorActionPreference = "Stop"

Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "🚀 Installing Codex CLI Ultimate Starter Kit..." -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan

# 1. Detect Codex Paths
$codexHome = Join-Path $env:USERPROFILE ".codex"
$configFile = Join-Path $codexHome "config.toml"
$backupFile = Join-Path $codexHome "config.toml.bak"

Write-Host "Checking Codex directory: $codexHome" -ForegroundColor Gray

if (-not (Test-Path $codexHome)) {
    Write-Host "Creating Codex home directory..." -ForegroundColor Yellow
    New-Item -ItemType Directory -Path $codexHome -Force | Out-Null
}

# 2. Backup current config.toml
if (Test-Path $configFile) {
    Write-Host "⚠️  Your existing config.toml will be backed up to config.toml.bak" -ForegroundColor Yellow
    Write-Host "   Custom MCP server configurations or profile overrides will need to be re-added." -ForegroundColor Yellow
    Write-Host "   Backing up current config.toml to $backupFile" -ForegroundColor Gray
    Copy-Item -Path $configFile -Destination $backupFile -Force
} else {
    Write-Host "No existing config.toml found, will create new." -ForegroundColor Gray
}

# 3. Copy default free profile to ~/.codex/config.toml
$workspaceRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$defaultProfile = Join-Path $workspaceRoot "config\free.toml"

if (Test-Path $defaultProfile) {
    Write-Host "Deploying 'free' profile as active config.toml..." -ForegroundColor Green
    Copy-Item -Path $defaultProfile -Destination $configFile -Force

    # Replace placeholders with actual paths
    $configContent = Get-Content $configFile -Raw
    $configContent = $configContent.Replace('__WORKSPACE_ROOT__', $workspaceRoot)
    Set-Content -Path $configFile -Value $configContent -Force
} else {
    Write-Error "Default profile not found at: $defaultProfile"
}

# 4. Find actual codex.exe
$codexExe = $null
# Try finding from config.toml.bak if it had it
if (Test-Path $backupFile) {
    $content = Get-Content $backupFile -Raw
    if ($content -match "CODEX_CLI_PATH\s*=\s*'([^']+)'") {
        $codexExe = $Matches[1]
    }
}

if (-not $codexExe) {
    $codexExe = (Get-Command codex.exe -ErrorAction SilentlyContinue).Source
}

if (-not $codexExe) {
    # Check default path under OpenAI runtimes
    $openaiDir = Join-Path $env:LOCALAPPDATA "OpenAI\Codex\bin"
    if (Test-Path $openaiDir) {
        $matches = Get-ChildItem -Path $openaiDir -Filter "codex.exe" -Recurse -ErrorAction SilentlyContinue
        if ($matches) {
            $codexExe = $matches[0].FullName
        }
    }
}

if (-not $codexExe) {
    Write-Host "⚠️ Warning: codex.exe not found in PATH or standard directories. Please make sure Codex CLI is installed." -ForegroundColor Yellow
    $codexExe = "codex" # Fallback to command name
} else {
    Write-Host "Found Codex CLI executable at: $codexExe" -ForegroundColor Green
}

# 5. Create wrapper scripts / CLI commands
$binDir = Join-Path $workspaceRoot "bin"
if (-not (Test-Path $binDir)) {
    New-Item -ItemType Directory -Path $binDir -Force | Out-Null
}

$wrapperName = "codex-installed.ps1"
$wrapperPath = Join-Path $binDir $wrapperName
$wrapperContent = @"
# Codex CLI Ultimate wrapper script for PowerShell
# Auto-generated by install.ps1 — do not edit manually.
# Re-run install.ps1 after updating Codex CLI to refresh the detected path.

param(
    [Parameter(ValueFromRemainingArguments = `$true)]
    `$RemainingArgs
)

# ── Resolve workspace root from script location ──────────────────
`$ScriptDir = Split-Path -Parent `$MyInvocation.MyCommand.Path
`$WorkspaceRoot = Resolve-Path (Join-Path `$ScriptDir "..")

# ── codex CLI — detected at install time ────────────────────────
`$CodexExe = "$codexExe"

# ── Fallback: try PATH if the installed binary moved ─────────────
if (-not (Test-Path `$CodexExe)) {
    try { `$CodexExe = (Get-Command codex.exe -ErrorAction Stop).Source } catch {}
}

# ── Dispatch sub-commands ────────────────────────────────────────
function Invoke-Script(`$Name) {
    `$path = Join-Path `$WorkspaceRoot "scripts" "`$Name.ps1"
    if (-not (Test-Path `$path)) {
        Write-Host "❌ Script not found: `$path" -ForegroundColor Red
        exit 1
    }
    # Pass all args except the first (command name) to the sub-script
    if (`$RemainingArgs.Count -gt 1) {
        & `$path `$RemainingArgs[1..(`$RemainingArgs.Count - 1)]
    } else {
        & `$path
    }
}

if (`$RemainingArgs.Count -gt 0) {
    switch (`$RemainingArgs[0]) {
        "profile" {
            if (`$RemainingArgs.Count -lt 2) {
                Write-Host "Usage: codex profile <name>" -ForegroundColor Yellow
                Write-Host "  Try: free, premium, local, ollama, openrouter" -ForegroundColor Gray
                Write-Host "Available profiles:" -ForegroundColor Gray
                Get-ChildItem (Join-Path `$WorkspaceRoot "config") -Filter "*.toml" | ForEach-Object {
                    Write-Host "  - `$(`$_.BaseName)" -ForegroundColor Cyan
                }
                return
            }
            Invoke-Script "switch-profile"
        }
        "doctor"   { Invoke-Script "doctor" }
        "update"   { Invoke-Script "update" }
        "benchmark" { Invoke-Script "benchmark" }
        "init"      { Invoke-Script "init-project" }
        "agent"     { Invoke-Script "load-agent" }
        default {
            if (-not `$CodexExe -or -not (Test-Path `$CodexExe)) {
                Write-Host "❌ codex.exe not found. Install Codex CLI or set CODEX_CLI_PATH." -ForegroundColor Red
                exit 1
            }
            & `$CodexExe `$RemainingArgs
        }
    }
} else {
    if (-not `$CodexExe -or -not (Test-Path `$CodexExe)) {
        Write-Host "❌ codex.exe not found. Install Codex CLI or set CODEX_CLI_PATH." -ForegroundColor Red
        exit 1
    }
    & `$CodexExe
}
"@

Set-Content -Path $wrapperPath -Value $wrapperContent -Force
Write-Host "Created Codex wrapper at: $wrapperPath" -ForegroundColor Green
Write-Host "The default template (bin/codex.ps1) also works standalone via PATH." -ForegroundColor Gray
Write-Host "It auto-detects codex.exe without needing installation." -ForegroundColor Gray

# 6. Auto-configure PATH
Write-Host "`n--- PATH Setup ---" -ForegroundColor Cyan

$binDirForPath = $binDir
$profileEntry = "`$env:Path = `"$binDirForPath;`$env:Path`""
$profilePath = $PROFILE.CurrentUserAllHosts

# Detect CI/non-interactive mode
$inCI = $env:CI -or $env:GITHUB_ACTIONS -or $env:TF_BUILD -or $env:APPVEYOR
if ($inCI) {
    Write-Host "Non-interactive mode detected (CI). Skipping PATH prompt." -ForegroundColor Gray
    Write-Host "To enable 'codex' command manually, add to your profile:" -ForegroundColor Gray
    Write-Host "  $profileEntry" -ForegroundColor White
}

$alreadyConfigured = $false
if ($profilePath -and (Test-Path $profilePath) -and -not $inCI) {
    $profileContent = Get-Content $profilePath -Raw -ErrorAction SilentlyContinue
    $alreadyConfigured = $profileContent -match [Regex]::Escape($binDirForPath)
}

if ($inCI) {
    # CI mode: just show instructions, no prompt
    Write-Host "  Manual setup:" -ForegroundColor Gray
    Write-Host "    $profileEntry" -ForegroundColor White
} elseif (-not $alreadyConfigured) {
    Write-Host "Would you like to add the bin directory to your PATH automatically?" -ForegroundColor Yellow
    Write-Host "  This adds '$binDir' to your PowerShell profile so 'codex' is always available." -ForegroundColor Gray
    Write-Host "  Answer Y to auto-configure, or N to do it manually." -ForegroundColor Gray

    try {
        $response = Read-Host "Add bin/ to PATH? (Y/N, default: Y)"
    } catch {
        $response = ""
    }

    if ($response -eq "" -or $response -match "^[Yy]") {
        try {
            $profileDir = Split-Path $profilePath -Parent
            if (-not (Test-Path $profileDir)) {
                New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
            }

            $entry = @"

# -- Codex CLI Ultimate ------------------------------------------
# Added by install.ps1 on $(Get-Date -Format 'yyyy-MM-dd')
$profileEntry
"@
            Add-Content -Path $profilePath -Value $entry -Encoding utf8
            Write-Host "✅ Added '$binDirForPath' to PowerShell profile: $profilePath" -ForegroundColor Green
            Write-Host "   Restart your terminal or run: . '$profilePath'" -ForegroundColor Gray
        } catch {
            Write-Host "⚠️  Could not update profile automatically: $($_.Exception.Message)" -ForegroundColor Yellow
            Write-Host "   Add this line manually to your PowerShell profile:" -ForegroundColor Gray
            Write-Host "   $profileEntry" -ForegroundColor White
        }
    } else {
        Write-Host "Skipping auto-configuration." -ForegroundColor Gray
        Write-Host "To enable 'codex' command manually, add this to your PowerShell profile:" -ForegroundColor Gray
        Write-Host "  $profileEntry" -ForegroundColor White
        Write-Host "  Profile path: $profilePath" -ForegroundColor Gray
    }
} elseif ($alreadyConfigured) {
    Write-Host "✅ bin directory already configured in your PowerShell profile." -ForegroundColor Green
}

# Also set for current session
$env:Path = "$binDirForPath;$env:Path"
Write-Host "✅ Added to current session PATH (temporary)." -ForegroundColor Green

# 7. Completion message
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "🎉 Setup Complete!" -ForegroundColor Green
Write-Host "Available commands:" -ForegroundColor Yellow
Write-Host "  codex profile free        - Switch to free OpenRouter" -ForegroundColor White
Write-Host "  codex profile premium     - Switch to premium OpenRouter" -ForegroundColor White
Write-Host "  codex profile local       - Switch to Ollama (local)" -ForegroundColor White
Write-Host "  codex profile ollama      - Switch to ollama.toml config" -ForegroundColor White
Write-Host "  codex profile openrouter  - Switch to openrouter.toml config" -ForegroundColor White
Write-Host "  codex doctor         - Run diagnostics" -ForegroundColor White
Write-Host "  codex init <name>    - Scaffold a new project" -ForegroundColor White
Write-Host "  codex benchmark      - Benchmark model latency" -ForegroundColor White
Write-Host "=========================================" -ForegroundColor Cyan
